# app = 'mirror-med-api'
# primary_region = 'sjc'
# swap_size_mb = 8192
# 
# [build]
# 
# [deploy]
#   strategy = "bluegreen"
# 
# [env]
# 
# # [[mounts]]
# #   source = 'data'
# #   destination = '/data'
# #   initial_size = '1GB'
# #   auto_extend_size_threshold = 80
# #   auto_extend_size_increment = '1GB'
# #   auto_extend_size_limit = '50GB'
# 
# [http_service]
#   internal_port = 8000
#   force_https = true
#   auto_stop_machines = 'stop'
#   auto_start_machines = true
#   min_machines_running = 1
#   processes = ['app']
# 
# [[http_service.checks]]
#   grace_period = "10s"
#   interval = "5s"
#   method = "GET"
#   timeout = "5s"
#   path = "/health"
# 
# [[vm]]
#   memory = '512mb'
#   cpu_kind = 'shared'
#   cpus = 1
# 
