# fly.toml app configuration file generated for med-mirror on 2025-07-14T20:49:12-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'med-mirror'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
